import java.util.*;

class NumberGame {

    public void guess() {
        Scanner sc = new Scanner(System.in);
        Random random = new Random();
        int RandomNumber = random.nextInt(100) + 1;
        System.out.println("Welcome to Number Game!");
        System.out.println();
        System.out.println("Guess the Number generated by Computer! between 1 to 100");
        int tryCount = 0;

        // logic

        while (true) {
            System.out.println("please enter a Number.");
            int userGuess = sc.nextInt();
            tryCount++;
            if (userGuess < 1 || userGuess > 100)
                System.out.println("Your guess is out of bounds. Try again.");
            else if (RandomNumber == userGuess) {
                System.out.println("Congrats! you Guess it Correct in " + tryCount + " tries");
                break;
            } else if (RandomNumber > userGuess)
                System.out.println("Nope! Think a Higher Number");
            else
                System.out.println("Nope! Think a Lower Number");
        }
    }

    public static void main(String args[]) {
        NumberGame ob = new NumberGame();
        ob.guess();
    }
}
